openapi: 3.0.3
info:
  title: Store-It - API de Gestión de Bodegas
  description: >
    Esta API permite gestionar las operaciones de la empresa **Store-It**, un sistema de administración de bodegas.
    Proporciona funcionalidades para registrar clientes, asignar espacios de almacenamiento, realizar movimientos de productos,
    gestionar contratos, consultar disponibilidad, generar reportes y manejar personal de ventas y recursos humanos.
    
    El sistema está diseñado para facilitar el manejo eficiente y seguro de las bodegas, ofreciendo servicios personalizados a empresas
    y usuarios que requieran almacenar mercancía de forma temporal o permanente.
  version: 1.0.0
  contact:
    url: https://github.com/MrZLeviatan/Store-It_Backend


servers:
  - url: http://localhost:8080/api
    description: Servidor local


paths:


components:
  schemas:
    Cliente:
      $ref: './components/Users.yaml#/components/schemas/Cliente'





