spring:
  datasource:
    # 🔹 URL de conexión a la base de datos
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}

    # 🔹 Nombre de usuario de la base de datos
    username: ${PGUSER}

    # 🔹 Contraseña de la base de datos
    password: ${PGPASSWORD}

    # 🔹 Driver JDBC para PostgreSQL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Puede ser update, create, validate, o none
      show-sql: true  # Muestra las consultas en la consola

