spring:
  datasource:
    # 🔹 Configuración para MySQL en Railway
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: fqfFnLXAHlHfDRmgwpMAiYyEBxFXrnru
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
