spring:
  datasource:
    # 🔹 URL de conexión a la base de datos
    url: postgresql://postgres:kStlbWGabRxiESSYUquziKqoxLIbFEJJ@trolley.proxy.rlwy.net:31433/railway

    # 🔹 Nombre de usuario de la base de datos
    username: postgres

    # 🔹 Contraseña de la base de datos
    password: kStlbWGabRxiESSYUquziKqoxLIbFEJJ

    # 🔹 Driver JDBC para PostgreSQL
    driver-class-name: org.postgresql.Driver

  jpa:
    # 🔹 Dialecto para PostgreSQL, necesario para Hibernate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      # 🔹 Controla las actualizaciones automáticas del esquema de Hibernate
      ddl-auto: update

